name: Build and Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    name: Build and Package for MacOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm install
      - run: npm run compile
      - run: npm run build:prod
      - run: npm run package:macos
      - uses: actions/upload-artifact@v1
        with:
          name: MoseAmp.dmg
          path: dist/MoseAmp.dmg

  build-windows:
    name: Build and Package for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm install
      - run: npm run compile
      - run: npm run build:prod
      - run: npm run package:windows
      - uses: actions/upload-artifact@v1
        with:
          name: MoseAmp.zip
          path: dist/MoseAmp.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: MoseAmp.dmg
      - uses: actions/download-artifact@v1
        with:
          name: MoseAmp.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload DMG
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: MoseAmp.dmg
          asset_name: MoseAmp.dmg
          asset_content_type: application/octet-stream
      - name: Upload EXE
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: MoseAmp.zip
          asset_name: MoseAmp.zip
          asset_content_type: application/octet-stream
